  version: '3'

  services:
    php:
      build:
        context: ./
      volumes:
        - ./:/app
      ports:
        - "8080:80"
      working_dir: /app

    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: hillel
      ports:
        - "3306:3306"
      volumes:
        - ./mysql:/var/lib/mysql